services:
  directus:
    image: docker.io/directus/directus
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      SECRET: ""
      ADMIN_EMAIL: ""
      ADMIN_PASSWORD: ""
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: "false"
      # CORS_ENABLED: 'true'
      # CORS_ORIGIN: '*'
      restart: always
# to create a new directus instance
# generate a secret key with: openssl rand -base64 32
# enter your email and password
# run: docker-compose up or podman-compose up -d
# -d to run in the background (detached mode)

# change database folder permissions if sqlite doesn't work
# same goes for uploads and extensions if they don't work by default
# chmod -R 777 database
# chmod -R 777 uploads
# chmod -R 777 extensions
